name: Manual Trigger2

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning
      tags:

jobs:
  printInputs:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo $(ls)
        echo "hoge"
