name: Manual Trigger TEST

defaults:
  run:
    shell: bash
    working-directory: tactics-board

on:
  workflow_dispatch:
    inputs:
      tags:
        required: true
        description: build tag
        default: latest

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: GCP Authenticate
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '273.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: echo tag
      run: echo ${{ github.event.inputs.tag }}

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: run
      run: |
        make build-deploy-dev
